name: Analyse Binary
on:
  workflow_dispatch:
  push:

jobs:
  analyse:
    name: Analyse Binary
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Analyse Binary
        shell: pwsh
        run: |
          echo "Running test.ps1"
          echo 1 | .\ida75\idapyswitch.exe
          $env:PYTHONHOME="C:\Miniconda"
          # New-ItemProperty -Path 'HKCU:\SOFTWARE\Hex-Rays\IDA' -Name 'License Hex-Rays SA. 銆愯珛鏀寔姝ｇ増銆? Unlimited License' -Value "1" -PropertyType DWORD -Force
          # Get-ItemProperty -path 'HKCU:\SOFTWARE\Hex-Rays\IDA' -Name 'Python3TargetDLL'
          reg import .\x.reg
          Get-ItemProperty -path 'HKCU:\SOFTWARE\Hex-Rays\IDA'
          Set-NetFirewallProfile -Profile Private -Enabled False
          Set-NetFirewallProfile -Profile Public -Enabled False
          .\ida75\ida64.exe -t
          # .\ida75\idat64.exe -B .\pwn3 2>&1 | tee .\ida.log
          ls

  