name: Analyse Binary
on:
  workflow_dispatch:
  push:

jobs:
  analyse:
    name: Analyse Binary
    runs-on: ubuntu-22.04
    env:
      binary: pwn3
    steps:
      - name: Update and Upgrade
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y zstd
      - name: Checkout
        uses: actions/checkout@v3

      - name: start docker and analyse
        run: |
          chmod +x analysis.sh
          docker run --rm --env BINARY=${{ env.binary }} --name ida-docker -p 8080:8080 -v ${{ github.workspace }}:/root/host nyamisty/docker-wine-ida:7.5sp3 /root/host/analysis.sh
          ls -la

      - name: Prepare Artifact
        run: |
          tar -cvf - ${{ env.binary }} | zstd - -o ${{ env.binary }}.tar.zst

      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.binary }}
          path: ${{ env.binary }}.tar.zst